import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const TermsOfService = () => {
  return (
    <div className="min-h-screen bg-slate-950 text-white">
      <div className="max-w-4xl mx-auto px-4 py-12">
        <Link to="/" className="inline-flex items-center gap-2 text-gray-400 hover:text-white mb-8">
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        
        <div className="space-y-6 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Intrex, you accept and agree to be bound by the terms and provision of this agreement. 
              If you do not agree to these terms, please do not use our service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">2. Service Description</h2>
            <p>
              Intrex provides AI-powered interview practice and feedback tools. Our platform analyzes your interview 
              performance including video, audio, and responses to provide automated feedback and scoring.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">3. User Responsibilities</h2>
            <p>Users agree to:</p>
            <ul className="list-disc list-inside ml-4 mt-2 space-y-2">
              <li>Use the service responsibly and ethically</li>
              <li>Provide accurate information during registration</li>
              <li>Not upload inappropriate or offensive content</li>
              <li>Not attempt to manipulate or abuse the AI analysis system</li>
              <li>Keep account credentials secure and confidential</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">4. AI-Generated Feedback</h2>
            <p>
              Users understand that interview feedback is generated by automated AI systems and may not always be 
              perfectly accurate. The feedback should be used as a guide for improvement and not as definitive 
              assessment of interview performance.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">5. Content Ownership</h2>
            <p>
              You retain ownership of all content you upload. By uploading content, you grant Intrex a license to 
              process, analyze, and store your content for the purpose of providing our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">6. Limitation of Liability</h2>
            <p>
              Intrex is provided "as is" without warranties of any kind. We are not liable for any damages arising 
              from the use of our service, including but not limited to interview outcomes or employment decisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">7. Changes to Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Continued use of the service after changes 
              constitutes acceptance of the modified terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">8. Contact</h2>
            <p>
              For questions about these terms, please contact us through our support channels.
            </p>
          </section>

          <p className="text-sm text-gray-500 mt-12">
            Last updated: {new Date().toLocaleDateString()}
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsOfService;
